# Descobrindo 5 funções no Pytorch
> "Recentimente iniciei um curso de Deep Learning pela oferecido pela @freeCodeCamp junto com @JovianML apresentado pelo @aakashns um brilhante instrutor, são seis semanas de curso Zero to GANS. Neste primeiro artigo exploro 5 funções que não conhecia no Pytorch, criando exemplos de aplicações utilizando cada função."


- toc:true
- branch: master
- badges: true
- comments: true
- author: Bruno de Abreu Machado
- categories: [pytorch, deep learning]






![](https://miro.medium.com/max/1000/1*FCArwuy8wAglYUXp04SN7g.png)

# Prevendo Temperatura


> Utilizando PyTorch crio uma rede neural simples para tentar realizar a predição de temperatura com dados do oceno, neste notebook/post explico cada etapa do processo de criação de uma rede neural simples com base no conteúdo aprendido no curso  de Deep Learning with PyTorch: Zero to GANs, oferecido pela @freeCodeCamp junto com @JovianML

- toc: true 
- badges: true 
- comments: true
- categories: [pytorch, deep learning]
- image: images/chart-preview.png

## Funções estudadas neste notebook

- torch.chain_matmul
- torch.cumprod
- torch.det
- torch.flatten
- torch.lu

### Imports

Como neste notebook vou explorar 5 funções do pytorch nesta sessão de **Imports** foi importado somente a lib `torch`

In [3]:
#collapse-hide
# Import torch and other required modules
import torch

Para descobrir novas funções utilizei o comando `dir(<lib>)` que listou todas as funções e o comando `help(torch.<func>)` para conhecer mais sobre ela.

In [11]:
#hide
print('Temos : ' + str(len(dir(torch))) + ' funções para explorar')
dir(torch)

Temos : 646 funções para explorar


['AVG',
 'AggregationType',
 'Argument',
 'ArgumentSpec',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'ByteStorage',
 'ByteTensor',
 'CharStorage',
 'CharTensor',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'CudaBoolStorageBase',
 'CudaByteStorageBase',
 'CudaCharStorageBase',
 'CudaDoubleStorageBase',
 'CudaFloatStorageBase',
 'CudaHalfStorageBase',
 'CudaIntStorageBase',
 'CudaLongStorageBase',
 'CudaShortStorageBase',
 'DictType',
 'DoubleStorage',
 'DoubleTensor',
 'ExecutionPlanState',
 'ExtraFilesMap',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'Function',
 'FunctionSchema',
 'Future',
 'Generator',
 'Gradient',
 'Graph',
 'GraphExecutorState',
 'HalfStorage',
 'HalfStorageBase',
 'HalfTensor',
 'IODescriptor',
 'IntStorage',
 'IntTensor',
 'IntType',
 'JITException',
 'ListType',
 'LockingLogger',
 'LoggerBase',
 'LongStorage',
 'LongTensor',
 'Node',
 'NoopLogger',
 'NumberType',
 'OptionalType',
 'PyTorchFileReader',
 'Py

In [5]:
#hide
help(torch.lu)

Help on function lu in module torch.functional:

lu(A, pivot=True, get_infos=False, out=None)
    Computes the LU factorization of a square matrix or batches of square matrices
    :attr:`A`. Returns a tuple containing the LU factorization and pivots of :attr:`A`.
    Pivoting is done if :attr:`pivot` is set to ``True``.
    
    .. note::
        The pivots returned by the function are 1-indexed. If :attr:`pivot` is ``False``,
        then the returned pivots is a tensor filled with zeros of the appropriate size.
    
    .. note::
        LU factorization with :attr:`pivot` = ``False`` is not available for CPU, and attempting
        to do so will throw an error. However, LU factorization with :attr:`pivot` = ``False`` is
        available for CUDA.
    
    .. note::
        This function does not check if the factorization was successful or not if
        :attr:`get_infos` is ``True`` since the status of the factorization is present in the
        third element of the return tuple.

## Primeira função - torch.chain_matmul

Uma das atividades mais utilizadas em *Deep Learning* é a multiplicação de matrizes e uma das funções que o *Pytorch* nos oferece para esta atividade é o `matmul` , onde nos oferece a oportundiade de realizar o produtor de 2 tensores. 

Nesta primeira função eu destaco a função `chain_matmul` que pode ser utilizada para realizar produtos de N tensors

Criamos 3 matrizes `2x2` utilizando a função `torch.randn` 

In [12]:
#collapse-show
# Example 1 - working 

matrix1 = torch.randn(3, 4)
matrix2 = torch.randn(4, 5)
matrix3 = torch.randn(5, 6)

# Sample
[matrix3, matrix1]

[tensor([[-1.0494,  0.4786, -0.2496, -0.9682, -1.1614, -1.6895],
         [ 0.4752, -0.0841, -1.4004,  0.0402, -0.5590, -0.9405],
         [ 0.5449,  1.5989,  0.5870, -1.2225, -0.3488, -0.2063],
         [ 2.5068, -1.1578,  0.4410, -1.4279,  1.5589, -0.1604],
         [-0.0883,  1.3295, -1.4044, -0.6259, -1.1656,  0.1526]]),
 tensor([[ 2.8613,  0.3382,  0.3099,  0.7402],
         [-0.6262, -1.3056,  0.6018, -0.6395],
         [-0.9182, -0.1888, -0.2580, -0.0872]])]

Para realizar a multiplicação simplesmente passamos as 3 matrizes como argumento.

Detalhe sobre as matrizes :
 * `matrix1` é uma matriz 3x4 : 3 linhas e 4 colunas
 * `matrix2` é uma matriz 4x5 : 4 linhas e 5 colunas
 * `matrix3` é uma matriz 5x6 : 5 linhas e 6 colunas
 
O resultado dessa multiplicação é uma nova matriz `3x6`, ou seja, 3 linhsa e 6 colunas. 



In [13]:
#collapse-show
# performing product
torch.chain_matmul(matrix1, matrix2, matrix3)

tensor([[-8.0324, -2.8931,  0.1645,  5.4147, -1.6135, -0.1331],
        [ 0.0715, -1.8514, -0.1220,  0.7759,  1.0616,  1.0326],
        [ 3.3314,  0.4199,  0.5218, -2.4496,  1.1681, -0.2269]])

Um segundo exemplo utilizando 4 matrizes maiores

In [14]:
#collapse-show
# Example 2 - working

matrix1 = torch.randn(100,110)
matrix2 = torch.randn(110,120)
matrix3 = torch.randn(120,130)
matrix4 = torch.randn(130,140)



# Sample
[matrix1, matrix2]

[tensor([[-1.0113,  2.7251,  0.1640,  ..., -1.1982,  0.2516,  2.3802],
         [-0.2575,  1.0712, -0.1683,  ...,  0.0799,  0.1335, -0.2284],
         [-0.4726,  1.4036, -1.6088,  ...,  0.3482,  0.6061, -0.0266],
         ...,
         [ 0.7878,  0.5653, -0.7980,  ..., -0.6144,  0.7365, -1.5773],
         [-1.2001, -2.0501,  0.2104,  ..., -1.2552,  0.2905, -0.4115],
         [ 0.7512,  1.0929, -0.1207,  ..., -2.0084, -0.8357, -1.8306]]),
 tensor([[-1.0272,  1.3241, -0.7045,  ...,  2.6188,  0.7776,  0.2609],
         [-2.2178,  0.2632, -1.0765,  ...,  1.0710, -0.0811, -0.6641],
         [ 0.8842, -0.5080,  0.2268,  ...,  0.1498,  0.2623, -1.1105],
         ...,
         [-1.0267,  0.8322, -1.3487,  ..., -0.7979, -1.6696, -0.4104],
         [ 0.9523, -0.4135, -0.2482,  ...,  0.6825, -1.1463, -0.7079],
         [ 0.0572,  0.5462,  0.4128,  ...,  1.1507,  1.1007,  2.5236]])]

Neste exemplo mostro como a função é eficiente, levando apenas `3.94ms` para realizar a multiplicação de todas as matrizes.

In [15]:
#collapse-show
# performing product
%time torch.chain_matmul(matrix1, matrix2, matrix3,matrix4)

CPU times: user 3.14 ms, sys: 802 µs, total: 3.94 ms
Wall time: 53.4 ms


tensor([[-1.0312e+03,  2.2024e+03,  8.7111e+02,  ..., -1.6845e+03,
         -1.8864e+03,  2.1999e+03],
        [-2.6746e+03, -1.2506e+03, -6.2687e+02,  ...,  1.6874e+03,
          2.2933e+03, -2.3796e+02],
        [ 2.0759e+02, -1.3513e+03, -1.8177e+03,  ..., -9.0427e+02,
         -1.5769e+03,  3.6219e+03],
        ...,
        [-3.3170e+01,  5.5390e+02,  4.1289e+02,  ..., -1.4384e+03,
          3.1857e+02,  5.0504e+03],
        [ 4.1570e+02, -1.2112e+03,  4.0855e+00,  ..., -3.3088e+02,
         -3.1520e+02, -1.3502e+03],
        [ 3.5522e+03, -1.2904e+03, -3.7685e+02,  ...,  1.6309e+02,
         -3.0861e+02, -3.3388e+02]])

No terceiro exemplo destaco um exemplo de falha, tentando realizar multiplicação de matrizes com dimensões diferentes. 

In [17]:
#collapse-show
# Example 3 - breaking 

matrix1 = torch.randn(3, 4)
matrix2 = torch.randn(4, 5, 4)

# Sample
[matrix2, matrix1]

[tensor([[[-1.3402, -1.3130, -0.3395,  0.5945],
          [-0.0259, -0.1071, -1.1639,  1.0613],
          [-0.7485, -1.1593, -1.5075, -1.0894],
          [-1.3146,  2.8806,  0.2349,  0.2622],
          [ 1.0905, -0.5099,  1.3923, -0.8981]],
 
         [[-0.7263, -0.2341, -0.5183,  0.3943],
          [ 0.6819,  0.1342,  0.0794, -0.0281],
          [-1.4046, -1.2519,  0.4766,  0.3968],
          [ 0.0881, -0.9358, -1.5493,  0.1794],
          [-1.0300,  0.8201, -0.2617,  0.7340]],
 
         [[-0.7806,  1.0247, -0.5675, -0.1108],
          [-0.5045, -1.4726,  0.6898, -0.2458],
          [ 0.1259, -0.9895,  1.2314,  0.3145],
          [ 0.0806,  1.2443, -0.9222,  0.2020],
          [-0.6894, -0.1846,  0.5644,  0.1418]],
 
         [[ 0.3160, -0.3909,  0.5069, -2.4691],
          [ 0.2330, -1.4668,  0.9580, -0.2209],
          [ 1.1199, -0.7593,  0.7848,  0.5991],
          [-0.3350, -1.3236, -0.7181,  0.7984],
          [-1.2864,  1.1569, -1.7247, -0.4536]]]),
 tensor([[ 0.5584,  1.1150, 

In [18]:
#collapse-show
torch.chain_matmul(matrix1, matrix2)

RuntimeError: Tensor dimension is 3, expected 2 instead.

Podemos ver que o output de erro do pytorch é bem explicativo, nos retornando que esperava um Tensor de 2D, duas dimensões e recebeu um Tensor 3D.

## Segunda função - torch.cumprod

This second function returns the cumulative product of elements

Nesta segunda função gostaria de destacar a função `torch.cumprod` , onde o nome é bem intuitivo quanto sua ação, isto mesmo , esta função realiza produto comulativo de tensores.

Para exemplificar, neste primeiro exemplo crio um tensor de dois números randomicos e utilizo a função `cumprod` para realizar o produto.

In [20]:
#collapse-show
# Example 1 - working

nums = torch.randn(2)
nums



tensor([-0.9611,  0.5437])

In [21]:
#collapse-show
torch.cumprod(nums,dim=0)

tensor([-0.9611, -0.5226])

Como pode ser observar o segundo elemento foi substituido pelo produto entre os dois números, nesta função também utilizo o argumento `dim=0`, que indica a dimensão da multiplicação.

In [22]:
#collapse-show
-0.9611 *  0.5437

-0.52255007

Neste segundo exemplo utilizando ainda a função `cumprod`, vamos realizar o produto cumulativo entre um tensor 3x3 :

In [99]:
#collapse-show
# Example 2 - working
nums = torch.randn(3,3)
nums

tensor([[ 1.8956, -1.4917, -0.9016],
        [-0.8868,  0.2748, -0.2181],
        [ 0.5888,  0.2202, -0.9849]])

In [115]:
#collapse-show
torch.cumprod(nums,dim=1)

tensor([[ 1.8956, -2.8277,  2.5494],
        [-0.8868, -0.2437,  0.0531],
        [ 0.5888,  0.1297, -0.1277]])

Abaixo a multiplicação realizada manualmente, utilizando um tensor `3x3` , utilizando `dim=1` , dimensão 1: 

In [119]:
#collapse-show
1.8956 * -1.4917 * -0.9016

2.549424134432

No terceiro exemplo mostro como se especificar uma dimensão inexistente teremos o seguinte resultado.

In [120]:
#collapse-show
# Example 3 - breaking

nums = torch.randn(3,3)
nums


tensor([[ 0.7083, -1.3484,  2.3374],
        [-0.1800, -0.2821,  1.4368],
        [ 0.8014, -1.1346, -0.7196]])

In [121]:
#collapse-show
torch.cumprod(nums,dim=9)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 9)

## Terceira função - torch.det

Esta terceira função é utilizada para calcular a determinante de uma matriz quadrada.

Por definição, uma matriz é considerada quadrada quando o número de colunas é igual ao número de linhas e esta associdada a um número que recebe a denominação de determinante .

Marcos Noe, no site [brasilescola.uol.com.br](https://brasilescola.uol.com.br/matematica/determinantes-1.htm), explica que :



> Note: O determinante de uma Matriz é dado pelo valor numérico resultante da subtração entre o somatório do produto dos termos da diagonal principal e do somatório do produto dos termos da diagonal secundária

In [126]:
# Example 1 - working

a = torch.tensor([[2,9],[-1,6.]])
a



tensor([[ 2.,  9.],
        [-1.,  6.]])

Neste primeiro exemplo tempos :
* A diagonal principal 2,6, onde o produto é  : `2 * 6 = 12`
* A diagonal secundária -1,9 , o produto será :  `-1 * 9 = -9 `
* E por fim a soma : `12 - (-9) = 21`

In [127]:
torch.det(a)

tensor(21.)

Neste segundo exemplo vamos ver uma matriz `3x3`

In [129]:
# Example 2 - working


A = torch.randn(3, 3)
A

tensor([[-0.1348, -1.0434,  0.0589],
        [ 0.2338,  1.0583, -0.1160],
        [-0.6723,  0.7773,  0.8919]])

In [130]:
torch.det(A)

tensor(0.0493)

Como pytorch trabalha com valores em *float* não podemos apresentar valores inteiros para a função pois como documentado ela espera um valor do time `float`

In [134]:
# Example 3 - breaking 

b = torch.tensor([[2,9],[-1,6]])
b

tensor([[ 2,  9],
        [-1,  6]])

In [135]:
torch.det(b)

RuntimeError: Expected a floating point tensor as input

## Quarta função - torch.flatten

Esta função é utilizada para transformar uma matriz em um vetor, ou seja, como demostrado no exemplo abaixo ela pega uma matriz 2x2 e transforma em um vetor unidimensional.


In [147]:
# Example 1 - working

T = torch.tensor([[1, 2],
                  [3, 4]])

T

tensor([[1, 2],
        [3, 4]])

In [148]:
torch.flatten(T)

tensor([1, 2, 3, 4])

Como podemos ver no segundo exemplo temos um tensor 2x2x2 , ou seja duas matrizes, neste caso ao realizar o `flatten` teremos o seguinte output:

In [157]:
# Example 2 - working


T = torch.tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])

T

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [159]:
torch.flatten(T, start_dim=1)


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Podemos utilizar como no exemplo o parametro `start_dim` para espeficicar a primera dimensão.

Abaixo teremos um exemplo onde não se pode aplicar o flatten quando range de dimensões não é válido.

In [162]:
# Example 3 - breaking 


T = torch.tensor([[1, 2],
                  [3, 4]])

T

tensor([[1, 2],
        [3, 4]])

In [165]:
torch.flatten(T, start_dim=2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

## Quinta função  - torch.lu

A última função que destaco, mas não menos importante é a `torch.lu` , esta interessante função retorna uma tupla contendo **LU factorization** e **pivots**, no primeiro exemplo criamos um tensor 2x3x3 e aplicamos a função:



In [184]:
# Example 1 - working

A = torch.randn(2, 3, 3)
A_LU, pivots = torch.lu(A, pivot=True)
A_LU



tensor([[[-0.8440,  0.3518, -0.0991],
         [ 0.6065, -1.2822, -1.2502],
         [-0.9766,  0.5978, -0.9145]],

        [[-0.4165,  1.0368, -0.7703],
         [ 0.3856, -0.8209, -0.9273],
         [-0.9241, -0.7736, -0.5355]]])

In [180]:
pivots

tensor([[3, 3, 3],
        [2, 2, 3]], dtype=torch.int32)

In [181]:
 A_LU, pivots, info = torch.lu(A, get_infos=True)
if info.nonzero().size(0) == 0:
    print('LU factorization succeeded for all samples!')

LU factorization succeeded for all samples!


In [182]:
info

tensor([0, 0], dtype=torch.int32)

Como todo exemplo quero mostrar uma utilização com erro, como podemos ver algumas opção só estão disponiveis para processamento em `GPU/CUDA`.

In [185]:
# Example 3 - breaking 

A = torch.randn(2, 3, 3)
A_LU, pivots = torch.lu(A, pivot=False)
A_LU



RuntimeError: lu without pivoting is not implemented on the CPU

## Conclusão

Aprendi muito ao pesquisar as funções da lib torch, minha jornada em Deep Learning está no começo mas é muito estimulante ver como é facil a utilização e documentação, apesar do notebook ser uma lista de 5 funções tive o prazer de estudar diversas outras como `torch.randn`.

Este notebook é a parte da primeira aula do curso [Zero to Gans](https://jovian.ml/forum/c/pytorch-zero-to-gans) oferecido pela @Jovian.ml e @freecodecamp, muito obrigado @aakashns pela brilhante aula.

Thank you @aakashns for the fantastic course.

## Reference Links
Algumas referencias :

* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


## Video aula 1 - Zero To Gans

> youtube: https://youtu.be/vo_fUOk-IKk